/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//RCC
#define  RCC_BASE        0x40021000
#define  RCC_APB2ENR     *(volatile  uint32_t*)(RCC_BASE + 0x18)
#define  RCC_CFGR        *(volatile  uint32_t*)(RCC_BASE + 0x04)
#define  RCC_CR          *(volatile  uint32_t*)(RCC_BASE + 0x00)
#define  RCC_IOPAEN      (1<<2)

//GPIOA
#define  PORTA_BASE      0x40010800
#define  GPIOA_CRL       *(volatile  uint32_t*)(PORTA_BASE + 0x00)
#define  GPIOA_CRH       *(volatile  uint32_t*)(PORTA_BASE + 0x04)
#define  GPIOA_ODR       *(volatile  uint32_t*)(PORTA_BASE + 0x0C)
#define  GPIOA13         (1UL<<13)

//EXTI
#define EXTI_BASE       0x40010400
#define EXTI_IMR        *(volatile  uint32_t*)(EXTI_BASE + 0x00)
#define EXTI_RTSR       *(volatile  uint32_t*)(EXTI_BASE + 0x08)
#define EXTI_PR         *(volatile  uint32_t*)(EXTI_BASE + 0x14)

//AFIO
#define AFIO_BASE      0x40010000
#define AFIO_EXTICR1   *(volatile  uint32_t*)(AFIO_BASE + 0x08)

//NVIC
#define NVIC_EXTIEN0   *(volatile  uint32_t*)(0xE000E100)

void clock_Init()
{
	//Enabling GPIO PORTA
	RCC_APB2ENR |= RCC_IOPAEN;
	//Enabling AFIO PORTA
	RCC_APB2ENR |= (1<<0);
}

void GPIO_Init()
{
	//PORTA PIN13 Output
	GPIOA_CRH &=  0xff0fffff;
	GPIOA_CRH |=  0x00100000;

	//PORTA PIN0 floating input (reset state)
	GPIOA_CRH |= (1<<2);
}

int main(void)
{
	GPIO_Init();
	clock_Init();
	//EXTI0 configuration to PORTA0
	AFIO_EXTICR1 = 0;

	//Enable Rising Trigger
	EXTI_RTSR |= (1<<0);

	//Enable line0 MASK
	EXTI_IMR |= (1<<0);

	//Enable NVIC IRQ6 for EXT0
	NVIC_EXTIEN0 |= (1<<6);

	for(;;);
}

void EXTI_IRQHandler()
{
	//Interupt Request is happened >>> PORTA / PIN0 / Rising_Egde
	//toggle led for PORTA PIN13
	GPIOA_ODR ^= (1<<13);

	//Clear Pending Request
	EXTI_PR |= (1<<0);
}
